name: fmcg_salesman_app
description: FMCG Salesman field app MVP (Flutter + Supabase)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  file_picker: ^10.3.10
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  battery_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
