/// A dealer/shop assigned to (or created by) a salesperson.
///
/// Naming note: `ownerNames`/`mobileNumber` are stored in the existing
/// `contact_person`/`contact_number` DB columns for the *first* owner
/// (kept for backward compatibility with older rows and any code that
/// still reads `contact_person` directly) — `contact_person` is written
/// as the first name in `ownerNames`. Everything else lives in columns
/// added by `add_dealer_fields_migration.sql` and
/// `add_dealer_fields_v2_migration.sql`.
class Outlet {
  final String id;
  final String name;
  final String? address;

  /// One or more owners — the "Add New Dealer" screen lets a salesperson
  /// add more than one.
  final List<String> ownerNames;

  final String? mobileNumber;
  final String? gstNumber;

  /// Kept for old rows created before dealer categories existed.
  /// No longer editable from the Add Dealer screen — see [dealerCategory].
  final String? businessType;

  /// e.g. 'General Store', 'Stationery', 'Medical Store', or a custom
  /// value the salesperson typed under "Other".
  final String? dealerCategory;

  final String? managerName;
  final String? managerPhone;
  final String? officeTelephone;
  final String? officeEmail;

  /// Free-form website or Instagram handle/link.
  final String? website;

  /// Stored as simple display strings (e.g. "10:00 AM") rather than a
  /// timezone-sensitive type, since this is a shop's stated hours, not
  /// an event on a calendar.
  final String? workingHoursFrom;
  final String? workingHoursTo;

  /// Day name (e.g. 'Sunday'), or null/'None' if the dealer has no
  /// weekly off.
  final String? weeklyOff;

  final String? shopFrontPhotoUrl;
  final String? businessCardPhotoUrl;
  final String? ownerPhotoUrl;

  /// Any additional photos beyond the three fixed slots above (e.g.
  /// interior, signage, stock shelf).
  final List<String> extraPhotoUrls;

  final double? latitude;
  final double? longitude;
  final String? routeId;

  Outlet({
    required this.id,
    required this.name,
    this.address,
    this.ownerNames = const [],
    this.mobileNumber,
    this.gstNumber,
    this.businessType,
    this.dealerCategory,
    this.managerName,
    this.managerPhone,
    this.officeTelephone,
    this.officeEmail,
    this.website,
    this.workingHoursFrom,
    this.workingHoursTo,
    this.weeklyOff,
    this.shopFrontPhotoUrl,
    this.businessCardPhotoUrl,
    this.ownerPhotoUrl,
    this.extraPhotoUrls = const [],
    this.latitude,
    this.longitude,
    this.routeId,
  });

  factory Outlet.fromJson(Map<String, dynamic> json) {
    List<String> stringList(dynamic v) {
      if (v == null) return const [];
      if (v is List) return v.map((e) => e.toString()).toList();
      if (v is String && v.trim().isNotEmpty) {
        return v
            .split(',')
            .map((e) => e.trim())
            .where((e) => e.isNotEmpty)
            .toList();
      }
      return const [];
    }

    return Outlet(
      id: json['id'],
      name: json['name'],
      address: json['address'],
      ownerNames: stringList(json['owner_names'] ?? json['contact_person']),
      mobileNumber: json['contact_number'],
      gstNumber: json['gst_number'],
      businessType: json['business_type'],
      dealerCategory: json['dealer_category'],
      managerName: json['manager_name'],
      managerPhone: json['manager_phone'],
      officeTelephone: json['office_telephone'],
      officeEmail: json['office_email'],
      website: json['website'],
      workingHoursFrom: json['working_hours_from'],
      workingHoursTo: json['working_hours_to'],
      weeklyOff: json['weekly_off'],
      shopFrontPhotoUrl: json['shop_front_photo_url'],
      businessCardPhotoUrl: json['business_card_photo_url'],
      ownerPhotoUrl: json['owner_photo_url'],
      extraPhotoUrls: stringList(json['extra_photo_urls']),
      latitude: (json['latitude'] as num?)?.toDouble(),
      longitude: (json['longitude'] as num?)?.toDouble(),
      routeId: json['route_id'],
    );
  }

  /// Convenience getter — first owner, for any screen that only wants
  /// to show a single name.
  String? get ownerName => ownerNames.isNotEmpty ? ownerNames.first : null;

  /// Map used when inserting a brand-new outlet. `id` is generated by the
  /// DB; `route_id` is left unset here — a salesperson's self-added shop
  /// is auto-stamped with their current route by a DB trigger, and an
  /// Admin adding one sets route_id explicitly via the service call.
  Map<String, dynamic> toInsertJson() {
    final cleanOwners =
        ownerNames.map((e) => e.trim()).where((e) => e.isNotEmpty).toList();
    return {
      'name': name,
      if (address != null && address!.isNotEmpty) 'address': address,
      if (cleanOwners.isNotEmpty) ...{
        'owner_names': cleanOwners,
        'contact_person': cleanOwners.first,
      },
      if (mobileNumber != null && mobileNumber!.isNotEmpty)
        'contact_number': mobileNumber,
      if (gstNumber != null && gstNumber!.isNotEmpty) 'gst_number': gstNumber,
      if (dealerCategory != null && dealerCategory!.isNotEmpty)
        'dealer_category': dealerCategory,
      if (managerName != null && managerName!.isNotEmpty)
        'manager_name': managerName,
      if (managerPhone != null && managerPhone!.isNotEmpty)
        'manager_phone': managerPhone,
      if (officeTelephone != null && officeTelephone!.isNotEmpty)
        'office_telephone': officeTelephone,
      if (officeEmail != null && officeEmail!.isNotEmpty)
        'office_email': officeEmail,
      if (website != null && website!.isNotEmpty) 'website': website,
      if (workingHoursFrom != null && workingHoursFrom!.isNotEmpty)
        'working_hours_from': workingHoursFrom,
      if (workingHoursTo != null && workingHoursTo!.isNotEmpty)
        'working_hours_to': workingHoursTo,
      if (weeklyOff != null && weeklyOff!.isNotEmpty) 'weekly_off': weeklyOff,
      if (shopFrontPhotoUrl != null) 'shop_front_photo_url': shopFrontPhotoUrl,
      if (businessCardPhotoUrl != null)
        'business_card_photo_url': businessCardPhotoUrl,
      if (ownerPhotoUrl != null) 'owner_photo_url': ownerPhotoUrl,
      if (extraPhotoUrls.isNotEmpty) 'extra_photo_urls': extraPhotoUrls,
      if (latitude != null) 'latitude': latitude,
      if (longitude != null) 'longitude': longitude,
    };
  }
}
