/// A dealer/shop assigned to (or created by) a salesperson.
///
/// Naming note: `ownerName`/`mobileNumber` are stored in the existing
/// `contact_person`/`contact_number` DB columns (they mean the same thing —
/// no migration needed to rename them). Everything else (GST, business
/// type, photos, GPS) lives in new columns added by
/// `add_dealer_fields_migration.sql`.
class Outlet {
  final String id;
  final String name;
  final String? address;
  final String? ownerName;
  final String? mobileNumber;
  final String? gstNumber;
  final String? businessType; // 'retailer' | 'wholesaler' | 'distributor'
  final String? shopFrontPhotoUrl;
  final String? businessCardPhotoUrl;
  final double? latitude;
  final double? longitude;
  final String? routeId;

  Outlet({
    required this.id,
    required this.name,
    this.address,
    this.ownerName,
    this.mobileNumber,
    this.gstNumber,
    this.businessType,
    this.shopFrontPhotoUrl,
    this.businessCardPhotoUrl,
    this.latitude,
    this.longitude,
    this.routeId,
  });

  factory Outlet.fromJson(Map<String, dynamic> json) {
    return Outlet(
      id: json['id'],
      name: json['name'],
      address: json['address'],
      ownerName: json['contact_person'],
      mobileNumber: json['contact_number'],
      gstNumber: json['gst_number'],
      businessType: json['business_type'],
      shopFrontPhotoUrl: json['shop_front_photo_url'],
      businessCardPhotoUrl: json['business_card_photo_url'],
      latitude: (json['latitude'] as num?)?.toDouble(),
      longitude: (json['longitude'] as num?)?.toDouble(),
      routeId: json['route_id'],
    );
  }

  /// Map used when inserting a brand-new outlet. `id` is generated by the
  /// DB; `route_id` is left unset here — a salesperson's self-added shop
  /// is auto-stamped with their current route by a DB trigger, and an
  /// Admin adding one sets route_id explicitly via the service call.
  Map<String, dynamic> toInsertJson() {
    return {
      'name': name,
      if (address != null && address!.isNotEmpty) 'address': address,
      if (ownerName != null && ownerName!.isNotEmpty)
        'contact_person': ownerName,
      if (mobileNumber != null && mobileNumber!.isNotEmpty)
        'contact_number': mobileNumber,
      if (gstNumber != null && gstNumber!.isNotEmpty) 'gst_number': gstNumber,
      if (businessType != null && businessType!.isNotEmpty)
        'business_type': businessType,
      if (shopFrontPhotoUrl != null) 'shop_front_photo_url': shopFrontPhotoUrl,
      if (businessCardPhotoUrl != null)
        'business_card_photo_url': businessCardPhotoUrl,
      if (latitude != null) 'latitude': latitude,
      if (longitude != null) 'longitude': longitude,
    };
  }
}
